
NOMBRE_asig =(input('ingrese su nombre de una asignatura : '))

NOMBRE =(input('ingrese su nombre: '))

Apellido=(input('ingrese su apellido: '))

NUMERO_ORDEN = int(input('ingrese su numero de orden:'))

calif_1 = int(input('ingrese su primera calificacion:'))

calif_2 = int(input('ingrese su segunda calificacion:'))

calif_3 = int(input('ingrese su tercera calificacion:'))

calif_4 = int(input('ingrese su cuarta calificacion:'))

promedio =(calif_1+calif_2+calif_3+calif_4)/4

print ('Su nombre es:', NOMBRE)

print('Su apellido es:',Apellido)

print('asignatura:',NOMBRE_asig)

print('su numero de orden es:', NUMERO_ORDEN)

print('Primera calificacion:',calif_1)

print('Segunda calificacion:',calif_2)

print('Tercera calificacion:', calif_3)

print('Cuarta calificacion:', calif_4)

print('El promedio de sus calificaciones es:', promedio)


